# maybe try a different verison? really running out of ideas here
version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: echoproject:latest
    container_name: "echoproject"
    ports:
      - "127.0.0.1:8888:8000"
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: echo
    command: sh -c './wait-for db:5432 -- ./main'
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: "postgres"
    ports:
      - 5168:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
