version: "3.8"
services:
  app:
    build: .
    container_name: "echoproject"
    ports:
      - 8888:5000
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: echo
    depends_on:
      - db
  db:
    image: "postgres"
    container_name: "postgres"
    ports:
      - 5168:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
